# Generated by Django 5.0.6 on 2024-05-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvertApp', '0002_remove_pdfconvertermodel_file_pdfconvertermodel_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfconvertermodel',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to='media/word/'),
        ),
    ]
