version: "3.8"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media  # Volume برای فایل‌های رسانه‌ای
    ports:
      - "8000:8000"
volumes:
  media_volume:
