# Generated by Django 5.0.6 on 2024-05-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvertApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfconvertermodel',
            name='file',
        ),
        migrations.AddField(
            model_name='pdfconvertermodel',
            name='pdf',
            field=models.FileField(default=1, upload_to='media/pdf/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfconvertermodel',
            name='word',
            field=models.FileField(default=1, upload_to='media/word/'),
            preserve_default=False,
        ),
    ]
